<?php
session_start();
include('connection.php');


//   Get the user id 
$user_id=$_SESSION['user_id'];


//  get the current time 
$time=time();

//  run a query to create a new note 
$sql="INSERT into notes (`user_id`,`note`,`time`) VALUES ('$user_id','','$time')";
$result=mysqli_query($link,$sql);
if(!$result)
{
    echo 'error';
}else 

{
    //  mysqli_inset_id  returns the autogenerated id  used in the last Query ! ;
    echo mysqli_insert_id($link);
}





?>